be more resilient when a package is not found in -Si
Throw a warning and continue to the next package.
By removing the exit command, many packages are now supported
as arguments to this option.

diff --git a/packer b/packer
--- a/packer
+++ b/packer
@@ -721,11 +721,10 @@ if [[ $option = info ]]; then
         results="$(sed -r "s|^(Version[^:]*:)(.*)$|\1$S${COLOR2}\2$S${ENDCOLOR}|" <<< "$results")"
         results="$(sed -r "s|^(URL[^:]*:)(.*)$|\1$S${COLOR4}\2$S${ENDCOLOR}|" <<< "$results")"
         results="$(sed -r "s|^[^ ][^:]*:|$S${COLOR1}&$S${ENDCOLOR}|" <<< "$results")"
-        echo -e "$results"
-        exit
+        echo -e "$results\n"
       else # Check to see if it is in the aur
         pkginfo "$package"
-        [[ -s "$tmpdir/$package.PKGBUILD" ]] || err "${COLOR7}error:${ENDCOLOR} package '$package' was not found"
+        [[ -s "$tmpdir/$package.PKGBUILD" ]] || { echo -e "${COLOR7}error:${ENDCOLOR} package '$package' was not found\n"; continue; }
         . "$tmpdir/$package.PKGBUILD"
 
         # Grap package ID
