Changes

diff --git a/packer b/packer
--- a/packer
+++ b/packer
@@ -2,7 +2,7 @@
 # Copyright Matthew Bruenig <matthewbruenig@gmail.com>
 # Licensed under GPL version 3
 
-[[ $PACMAN ]] || PACMAN="pacman"
+[[ $PACMAN_CLIENT ]] || PACMAN_CLIENT="pacman"
 
 # set tmpfile stuff, clean tmpdir
 tmpdir="${TMPDIR:-/tmp}/packertmp-$UID"
@@ -298,9 +298,9 @@ aurinstall() {
 
   [[ $? -ne 0 ]] && echo "The build failed." && return 1
   if  [[ $2 = dependency ]]; then
-    runasroot $PACMAN ${PACOPTS[@]} --asdeps -U $pkgname-*$PKGEXT
+    runasroot $PACMAN_CLIENT ${PACOPTS[@]} --asdeps -U $pkgname-*$PKGEXT
   elif [[ $2 = explicit ]]; then
-    runasroot $PACMAN ${PACOPTS[@]} -U $pkgname-*$PKGEXT
+    runasroot $PACMAN_CLIENT ${PACOPTS[@]} -U $pkgname-*$PKGEXT
   fi
 }
 
@@ -353,7 +353,7 @@ installhandling() {
  
   # First install the explicit pacman packages, let pacman prompt
   if [[ $pacmanpackages ]]; then
-    runasroot $PACMAN "${PACOPTS[@]}" -S -- "${pacmanpackages[@]}"
+    runasroot $PACMAN_CLIENT "${PACOPTS[@]}" -S -- "${pacmanpackages[@]}"
   fi
   if [[ -z $aurtargets ]]; then
     exit
@@ -399,7 +399,7 @@ installhandling() {
 
   # Install pacman dependencies
   if [[ $pacmandepends ]]; then
-    runasroot $PACMAN --noconfirm --asdeps -S -- "${pacmandepends[@]}" || err "Installation failed."
+    runasroot $PACMAN_CLIENT --noconfirm --asdeps -S -- "${pacmandepends[@]}" || err "Installation failed."
   fi 
 
   # Install aur dependencies
@@ -479,7 +479,7 @@ if [[ $option = update ]]; then
   sourcemakepkgconf
   # Pacman update
   if ! [[ $auronly ]]; then
-    runasroot $PACMAN "${PACOPTS[@]}" "$pacmanarg"
+    runasroot $PACMAN_CLIENT "${PACOPTS[@]}" "$pacmanarg"
   fi
 
   # Aur update
